batch_size: 32
num_workers: 16
lr: 1e-4
weight_decay: 1e-2
#mri_dataset: 'dataset/mri_v5.2_Rigid.hdf5'
mri_dataset: 'dataset/2c_mri_v5.2_Rigid.hdf5'
augmentation: True
#tabular_dataset: 'dataset/img/'
tabular_dataset: 'dataset/img/2c_'
early_stop: 100
max_epoch: 500

vq_gan_checkpoint: "log/vq_gan_mri/version_30/checkpoints/latest_checkpoint.ckpt"
#vq_gan_checkpoint:
#ddpm_checkpoint: "log/LcDDPM/version_11/checkpoints/epoch=999-step=17000.ckpt"
ddpm_checkpoint:
tabular: False

num_layers: 4
base_channels: 8
channel_multiplier: 1.5
cnn_dropout_rate: 0.0
fc_dropout_rate: 0.4
fc_hidden: 64
embed_dim: 32
num_classes: 2