batch_size: 32
num_workers: 16
lr: 1e-4
eta_min: 1e-6
dataset: 'dataset/mri_pet_v5.2_Rigid.hdf5'
#early_stop: 100
max_epochs: 1000
mri_vqgan_checkpoint: "log/vq_gan_mri/version_38/checkpoints/latest_checkpoint.ckpt"
pet_vqgan_checkpoint: "log/vq_vae_pet/version_0/checkpoints/latest_checkpoint.ckpt"

input_size: 32
depth_size: 32
channel_mult: "1,2"
num_channels: 256
num_res_blocks: 2
attention_resolutions:
num_heads: 1
#save_and_sample_every: 1000
timesteps: 50
in_channels: 64
out_channels: 32