batch_size: 32
num_workers: 16
lr: 1e-4
eta_min: 1e-5
dataset: 'dataset/mri_pet_label_v5.1_Rigid.hdf5'
#early_stop: 100
max_epochs: 1000
mri_vqgan_checkpoint: "log/vq_gan_mri/version_116/checkpoints/latest_checkpoint.ckpt"
pet_vqgan_checkpoint: "log/vq_gan_pet/version_9/checkpoints/latest_checkpoint.ckpt"

input_size: 16
depth_size: 16
channel_mult: "1,2"
num_channels: 128
num_res_blocks: 2
attention_resolutions:
num_heads: 1
#save_and_sample_every: 1000
timesteps: 250
in_channels: 64
out_channels: 32