seed: 1234
batch_size: 16
num_workers: 16
image_type: 'pet'  # 'pet' or 'mri'
#dataset: 'dataset/mri_v5.2_Rigid.hdf5'
dataset: 'dataset/mri_pet_label_v5.1_Rigid.hdf5'
image_channels: 1

accumulate_grad_batches: 1
max_steps: -1
max_epochs: 300
precision: 16-mixed
gradient_clip_val: 1.0

embedding_dim: 16
n_codes: 2048
n_hiddens: 8
lr: 5e-3
eta_min: 1e-3
num_groups: 32
norm_type: group


